config/routes.rb
Rails.application.routes.draw do
  root 'public#index'
  get 'show/:permalink', to: 'public#show', as: 'public_show'

  get 'admin', to: 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, except: :show do
    member { get :delete }
  end

  resources :subjects do
    member { get :delete }
  end

  resources :pages do
    member { get :delete }
  end

  resources :sections do
    member { get :delete }
  end

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
end

app/models/section.rb
# The section contains all the content for a page in html or txt
class Section < ApplicationRecord

  acts_as_list scope: :page

  belongs_to :page
  has_many :section_edits
  has_many :admin_users, through: :section_edits

  scope :visible, -> { where(visible: true) }
  scope :invisible, -> { where(visible: false) }
  scope :sorted, -> { order('position ASC') }
  scope :newest_first, -> { order('created_at DESC') }

  CONTENT_TYPES = %w[text HTML].freeze

  validates_presence_of :name
  validates_length_of :name, maximum: 255
  validates_inclusion_of :content_type,
                         in: CONTENT_TYPES,
                         message: "must be one of: #{CONTENT_TYPES.join(', ')}"
  validates_presence_of :content
end

app/controllers/sections_controller.rb
# CRUD Operations for sections as a nested object to pages
class SectionsController < ApplicationController
  layout 'admin'

  before_action :confirm_logged_in
  # To prevent having to define a section many times throughout this controller
  # use a private method to find the section for us.
  before_action :find_section, only: %i[show edit update delete destroy]
  before_action :find_page
  before_action :set_section_count, only: %i[new create edit update]

  def index
    @sections = @page.sections.sorted
  end

  def show; end

  def new
    @page = Page.find_by_id(@page.id)
    @section = @page.sections.build(page_id: @page.id)
  end

  def create
    @section = Section.new(section_params)
    @section.page_id = @page.id

    if @section.save
      flash[:notice] = 'Section saved successfully.'
      redirect_to sections_path(page_id: @page.id)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @section.update_attributes(section_params)
      flash[:notice] = 'Section updated successfully.'
      redirect_to section_path(@section, page_id: @page.id)
    else
      render :edit
    end
  end

  def delete; end

  def destroy
    @section.destroy

    flash[:notice] = "Section '#{@section.name}' successfully destroyed."
    redirect_to sections_path(page_id: @page.id)
  end

  private

  def set_section_count
    @section_count = @page.sections.count
    @section_count += 1 if params[:action].in? %w[new create]
  end

  def section_params
    params.require(:section).permit(
        :name, :content_type, :position, :visible, :content
    )
  end

  def find_section
    @section ||= Section.find(params[:id])
  end

  def find_page
    @page = Page.find(params[:page_id])
  end

end

app/views/sections/_back_to_index.html.erb
<%= link_to('<< Back to Sections', sections_path(page_id: @page.id), class: 'back-link') %>

app/views/sections/_form.html.erb
<%= error_messages_for(f.object) %>

<div class="table" summary="section form fields">
  <div>
    <%= f.label(:position,) %>
    <%= f.select(:position, 1..@section_count) %>
  </div>

  <div>
    <%= f.label(:name) %>
    <%= f.text_field(:name) %>
  </div>

  <div>
    <%= f.label(:content) %>
    <%= f.text_area(:content, size: '40x10') %>
  </div>

  <div>
    <%= f.label(:content_type) %>
    <div class="inline-form">
      <%= f.radio_button(:content_type, 'text') %>
      <%= f.label(:content_type_text, 'Text') %>
      <%= f.radio_button(:content_type, 'HTML') %>
      <%= f.label(:content_type_html, 'Html')%>
    </div>
  </div>

  <div>
    <div class="inline-form">
      <%= f.label(:page, value: 'Belongs to page:')%>
      <%= f.object.page.name %>
    </div>
  </div>

  <div>
    <div class="inline-form">
      <%= f.label(:visible) %>
      <%= f.check_box(:visible) %>
    </div>
  </div>

</div>

app/views/sections/delete.html.erb
<%= render 'shared/title' %>

<div class="sections delete">
  <h2>Delete Section <%= @section.name %></h2>

  <%= link_to('<< Back to Sections', sections_path(page_id: @page) ) %>

  <%= form_for(@section, url: section_path(@section, page_id: @page.id), method: 'delete') do |f| %>
    <p>Are you sure you want to permanently delete this section?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit('Delete Section') %>
    </div>
  <% end %>
</div>

app/views/sections/edit.html.erb
<%= render 'shared/title' %>

<div class="sections edit">
  <h2>Update Section <%= @section.name %></h2>

  <%= render partial: 'back_to_index', locals: {page: @page} %>

  <%= form_for(@section, url: section_path(@section, page_id: @page.id)) do |f| %>
    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit('Update Section') %>
    </div>
  <% end %>
</div>

app/views/sections/index.html.erb
<%= render 'shared/title' %>

<div class="sections index">
  <h2>Sections</h2>
  <%= link_to('<< To Admin Menu', access_menu_path, class: 'admin-menu') %>
  <br/>
  <%= link_to('<< To Pages', pages_path(subject_id: @page.subject.id), class: 'action index') %>
  <crud-table id="table-sections">
    <headers class="table-sections">
      <p>#</p>
      <p>Name</p>
      <p>Page ID</p>
      <p>Visible</p>
      <p>Actions</p>
    </headers>
    <data>
      <% @sections.each do |s| %>
        <data-segment class="table-sections">
          <p><%= s.position %></p>
          <p><%= s.name%></p>
          <p class='center tiny-cell'><%= s.page_id %></p>
          <p class='center tiny-cell'><%= status_tag(s.visible) %></p>
          <p class='actions'>
            <%= link_to('Show', section_path(s, page_id: @page.id), class: 'action show') %> |
            <%= link_to('Edit', edit_section_path(s, page_id: @page.id), class: 'action edit') %> |
            <%= link_to('Delete', delete_section_path(s, page_id: @page.id), class: 'action delete') %>
          </p>
        </data-segment>
      <% end %>
    </data>
  </crud-table>
  <%= link_to('Add new section', new_section_path(page_id: @page.id), class: 'action new')%>
</div>

app/views/sections/new.html.erb
<%= render 'shared/title' %>

<div class="sections new">
  <h2>Create new Section</h2>

  <%= render partial: 'back_to_index', locals: {page: @page} %>

  <%= form_for(@section, url: sections_path(page_id: @page.id)) do |f| %>
    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit('Create Section') %>
    </div>
  <% end %>
</div>

app/views/sections/show.html.erb
<%= render 'shared/title' %>

<div class="sections show">
  <h2>Showing Section <%= @section.name %></h2>

  <%= render partial: 'back_to_index', locals: {page: @page} %>

  <table summary="Section detail view">
    <tr>
      <th>Position</th>
      <td><%= @section.position %></td>
    </tr>

    <tr>
      <th>Name</th>
      <td><%= @section.name %></td>
    </tr>

    <tr>
      <th>Content</th>
      <td><%= @section.content %></td>
    </tr>

    <tr>
      <th>Content Type</th>
      <td><%= @section.content_type %></td>
    </tr>

    <tr>
      <th>Page</th>
      <td><%= @section.page_id %></td>
    </tr>

    <tr>
      <th>Visible</th>
      <td><%= status_tag(@section.visible) %></td>
    </tr>

    <tr>
      <th>Created</th>
      <td><%= @section.created_at %></td>
    </tr>

    <tr>
      <th>Updated</th>
      <td><%= @section.updated_at %></td>
    </tr>
  </table>

</div>