config/routes.rb
Rails.application.routes.draw do
  root 'public#index'
  get 'show/:permalink', to: 'public#show', as: 'public_show'

  get 'admin', to: 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, except: :show do
    member { get :delete }
  end

  resources :subjects do
    member { get :delete }
  end

  resources :pages do
    member { get :delete }
  end

  resources :sections do
    member { get :delete }
  end

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
end

app/views/pages/_back_to_index.html.erb
<%= link_to('<< Back to Pages', pages_path(subject_id: @subject.id), class: 'back-link') %>

app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>

<div class="table" summary="pages form fields">
  <div>
    <%= f.label(:position) %>
    <%= f.select(:position, 1..@page_count) %>
  </div>

  <div>
    <%= f.label(:name) %>
    <%= f.text_field(:name) %>
  </div>

  <div>
    <%= f.label(:permalink) %>
    <%= f.text_field(:permalink) %>
  </div>

  <div>
    <%= f.label(:subject) %>
    <%= f.object.subject.name %>
  </div>

  <div>
    <%= f.label(:visible) %>
    <%= f.check_box(:visible) %>
  </div>
</div>

app/views/pages/delete.html.erb
<%= render 'shared/title' %>

<div class="pages delete">
  <h2>Delete Page <%= @page.name %></h2>

  <%= render partial: 'back_to_index', locals: {subject: @subject} %>

  <%= form_for(@page, url: page_path(@page, subject_id: @subject.id), method: 'delete') do |f| %>
    <p>Are you sure you want to permanently delete this page?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit('Delete Page') %>
    </div>
  <% end %>
</div>

app/views/pages/edit.html.erb
<%= render 'shared/title' %>

<div class="pages edit">
  <h2>Update Page <%= @page.name %></h2>

  <%= render partial: 'back_to_index', locals: {subject: @subject} %>

  <%= form_for(@page, url: page_path(@page, subject_id: @subject.id)) do |f| %>
    <%= render(partial: 'form', locals: { f: f }) %>

    <div class="form-buttons">
      <%= f.submit('Update Page') %>
    </div>
  <% end %>
</div>

app/views/pages/index.html.erb
<%= render 'shared/title' %>

<div class="pages index">
  <h2>Pages</h2>
  <%= link_to('<< To Admin Menu', access_menu_path, class: 'admin-menu')%>
  <br/>
  <%= link_to('<< To Subjects', subjects_path, remote: true, class: 'action index')%>
  <crud-table id="table-pages">
    <headers class="table-pages">
        <p>#</p>
        <p>Name</p>
        <p>Permalink</p>
        <p>Subject ID</p>
        <p>Sections</p>
        <p>Visible</p>
        <p>Actions</p>
    </headers>
    <data>
      <% @pages.each do |p| %>
        <data-segment class="table-pages">
          <p><%= p.position %></p>
          <p><%= p.name%></p>
          <p><%= p.permalink %></p>
          <p><%= p.subject_id %></p>
          <p class='center'><%= link_to(p.sections.size, sections_path(page_id: p.id), class: 'action index') %></p>
          <p class='center'><%= status_tag(p.visible) %></p>
          <p class='actions'>
            <%= link_to('Show', page_path(p, subject_id: @subject.id), class: 'action show') %> |
            <%= link_to('Edit', edit_page_path(p, subject_id: @subject.id), class: 'action edit') %> |
            <%= link_to('Delete', delete_page_path(p, subject_id: @subject.id), class: 'action delete') %>
          </p>
        </data-segment>
      <% end %>
    </data>
  </crud-table>
  <%= link_to('Add new page', new_page_path(subject_id: @subject.id), class: 'action new')%>
</div>

app/views/pages/new.html.erb
<%= render 'shared/title' %>

<div class="pages new">
  <h2>Create a new Page</h2>

  <%= render partial: 'back_to_index', locals: {subject: @subject} %>

  <%= form_for(@page, url: pages_path(subject_id: @subject.id)) do |f| %>
    <%= render(partial: 'form', locals: { f: f }) %>

    <div class="form-buttons">
      <%= f.submit('Create Page') %>
    </div>
  <% end %>
</div>

app/views/pages/show.html.erb
<%= render 'shared/title' %>

<div class="pages show">
  <h2>Showing Page <%= @page.name %></h2>

  <%= render partial: 'back_to_index', locals: {subject: @subject} %>

  <table summary="Page detail view">
    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>

    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>

    <tr>
      <th>Permalink</th>
      <td><%= @page.permalink %></td>
    </tr>

    <tr>
      <th>Subject ID</th>
      <td><%= @page.subject_id %></td>
    </tr>

    <tr>
      <th>Visible</th>
      <td><%= status_tag(@page.visible) %></td>
    </tr>

    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>

    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>

</div>