config/routes.rb
Rails.application.routes.draw do
  root 'public#index'
  get 'show/:permalink', to: 'public#show', as: 'public_show'

  get 'admin', to: 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, except: :show do
    member { get :delete }
  end

  resources :subjects do
    member { get :delete }
  end

  resources :pages do
    member { get :delete }
  end

  resources :sections do
    member { get :delete }
  end

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
# Subjects are allow for the grouping of pages in the navigation
class Subject < ApplicationRecord

  acts_as_list

  has_many :pages

  scope :visible, -> { where(visible: true) }
  scope :invisible, -> { where(visible: false) }
  scope :sorted, -> { order('position ASC') }
  scope :newest_first, -> { order('created_at DESC') }
  scope :search, ->(query) { where(['name LIKE ?', "%#{query}%"]) }

  validates :name,        presence: true,
                          length: { maximum: 255 }
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  layout 'admin'

  before_action :confirm_logged_in
  # To prevent having to define a subject many times throughout this controller
  # use a private method to find the subject for us.
  before_action :find_subject, only: %i[show edit update delete destroy]

  def index
    @subjects = Subject.sorted
  end

  def show; end

  def new
    @subject_count = Subject.count + 1
    @subject = Subject.new
  end

  def create
    # Instantiate a new object using form params
    @subject = Subject.new(subject_params)

    # Save the object
    if @subject.save
      # If save succeeds redirect to index action
      flash[:notice] = 'Subject created successfully.'
      redirect_to subjects_path
    else
      @subject_count = Subject.count + 1
      render :new
    end
  end

  def edit
    @subject_count = Subject.count
  end

  def update
    # Update the object
    if @subject.update_attributes(subject_params)
      # If update succeeds redirect to show action
      flash[:notice] = 'Subject updated successfully.'
      redirect_to subject_path(@subject)
    else
      @subject_count = Subject.count
      # render edit if errors
      render :edit
    end
  end

  def delete; end

  def destroy
    @subject.destroy

    flash[:notice] = "Subject '#{@subject.name}' destroyed successfully"
    redirect_to subjects_path
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :position, :visible)
  end

  def find_subject
    @subject ||= Subject.find(params[:id])
  end
end

app/views/subjects/_back_to_index.html.erb
<%= link_to('<< Back to Subjects', subjects_path, remote: true, class: 'back-link') %>

app/views/subjects/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Subject form fields">
  <tr>
    <th><%= f.label(:name) %></th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th><%= f.label(:position) %></th>
    <td><%= f.select(:position, 1..@subject_count) %></td>
  </tr>
  <tr>
    <th><%= f.label(:visible) %></th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
</table>

app/views/subjects/_index.html.erb
<%= render 'shared/title' %>

<div class="subjects index">
  <h2>Subjects</h2>
  <%= link_to('<< To Admin Menu', access_menu_path, class: 'admin-menu')%>
  <table id="table-subjects">
    <thead>
      <tr>
        <th>#</th>
        <th>Subject</th>
        <th>Visible</th>
        <th>Pages</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @subjects.each do |s| %>
        <tr>
          <td><%= s.position %></td>
          <td><%= s.name%></td>
          <td class='center'><%= status_tag(s.visible)%></td>
          <td class='center'><%= s.pages.size %></td>
          <td class='actions'>
            <%= link_to('View Pages', pages_path(subject_id: s.id), class: 'action show') %> |
            <%= link_to('Show',       subject_path(s),                    class: 'action show') %> |
            <%= link_to('Edit',       edit_subject_path(s),               class: 'action edit') %> |
            <%= link_to('Delete',     delete_subject_path(s),             class: 'action delete') %>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>
  <%= link_to('Add new subject', new_subject_path, class: 'action new')%>
</div>

app/views/subjects/delete.html.erb
<%= render 'shared/title' %>
<%= render partial: 'back_to_index', locals: {format: 'html'}%>

<div class="subjects delete">
  <h2>Delete Subject <%= @subject.name %></h2>

  <%= form_for(@subject, method: 'delete') do |f| %>
    <p>Are you sure you want to permanently delete this subject?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit('Delete Subject') %>
    </div>
  <% end %>
</div>

app/views/subjects/edit.html.erb
<%= render 'shared/title' %>
<div class="subjects edit">
  <h2>Update Subject <%= @subject.name %></h2>

  <%= render partial: 'back_to_index' %>

  <%= form_for(@subject) do |f| %>
    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit('Update Subject') %>
    </div>
  <% end %>
</div>

app/views/subjects/index.html.erb
<%= render 'shared/title' %>

<div class="subjects index">
  <h2>Subjects</h2>
  <%= link_to('<< To Admin Menu', access_menu_path, class: 'admin-menu')%>
  <crud-table id="table-subjects">
    <headers class="table-subjects">
      <p>#</p>
      <p>Subject</p>
      <p>Visible</p>
      <p>Pages</p>
      <p>Actions</p>
    </headers>
    <data>
      <% @subjects.each do |s| %>
        <data-segment class="table-subjects">
          <p><%= s.position %></p>
          <p><%= s.name%></p>
          <p><%= status_tag(s.visible)%></p>
          <p><%= link_to(s.pages.size, pages_path(subject_id: s.id), class: 'action show')%></p>
          <p class='actions'>
            <%= link_to('Show',       subject_path(s),                    class: 'action show') %> |
            <%= link_to('Edit',       edit_subject_path(s),               class: 'action edit') %> |
            <%= link_to('Delete',     delete_subject_path(s),             class: 'action delete') %>
          </p>
        </data-segment>
      <% end %>
    </data>

  </crud-table>
  <%= link_to('Add new subject', new_subject_path, class: 'action new')%>
</div>

app/views/subjects/new.html.erb
<%= render 'shared/title' %>

<div class="subjects new">
  <h2>Create a new Subject</h2>

  <%= render partial: 'back_to_index' %>

  <%= form_for(@subject) do |f| %>
    <%= render(partial: 'form', locals: {f: f}) %>

    <div class="form-buttons">
      <%= f.submit('Create Subject', remote:true) %>
    </div>
  <% end %>
</div>

app/views/subjects/show.html.erb
<%= render 'shared/title' %>

<div class="subjects show">
  <h2>Showing Subject <%= @subject.name %></h2>

  <%= render partial: 'back_to_index' %>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= status_tag(@subject.visible) %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>

</div>