config/routes.rb
Rails.application.routes.draw do
  root 'public#index'
  get 'show/:permalink', to: 'public#show', as: 'public_show'

  get 'admin', to: 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, except: :show do
    member { get :delete }
  end

  resources :subjects do
    member { get :delete }
  end

  resources :pages do
    member { get :delete }
  end

  resources :sections do
    member { get :delete }
  end

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div id="copyright">
    <p>copyright &copy; 2020 Danny Oosthoek</p>
  </div>
</div>

app/views/layouts/_headers.html.erb
<input type="checkbox" id="navigation-toggle" />
<div id="navigation" >
    <%= render(partial: 'layouts/navigation', locals: {subjects: @subjects, origin: origin} ) %>
</div>
<div id="animator">
  <label for="navigation-toggle">
    <%= render partial: 'layouts/menu_image' %>
  </label>
</div>

app/views/layouts/_menu_image.html.erb
<svg version="1.2" baseProfile="tiny" id="full-animation" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 300 212">
  <g id="backdrop-ruby-curve">
    <path d="M149.616,210.019c40.253,0,72.884-32.631,72.884-72.884h20.25l8.771-14.239h28.124l16.022-16.022h-55.886
	l-5.198,9h-14.791c-8.058-27.411-32.09-47.972-61.332-50.94l16.618-13.261L149.616,4.25l-25.463,47.421l16.618,13.261
	c-29.242,2.969-53.274,23.53-61.332,50.94H64.648l-5.198-9H3.564l16.022,16.022h28.124l8.771,14.239h20.25
	C76.732,177.388,109.363,210.019,149.616,210.019z" id="backdrop2"></path>
    <path d="M149.616,210.019c40.253,0,72.884-32.631,72.884-72.884h20.25l8.771-14.239h28.124l16.022-16.022h-55.886
	l-5.198,9h-14.791c-8.058-27.411-32.09-47.972-61.332-50.94l16.618-13.261L149.616,4.25l-25.463,47.421l16.618,13.261
	c-29.242,2.969-53.274,23.53-61.332,50.94H64.648l-5.198-9H3.564l16.022,16.022h28.124l8.771,14.239h20.25
	C76.732,177.388,109.363,210.019,149.616,210.019z" id="backdrop"></path>
    <polygon points="150,59.338 138.74,48.695 150,22.305 161.26,48.695 " id="outer-ruby"></polygon>
    <polygon points="150,53.973 143.329,47.639 150,31.102 156.672,47.639 " id="inner-ruby"></polygon>
    <path d="M149.576,204.516c-31.871,0-59.633-22.627-66.013-53.802c-0.083-0.404,0.178-0.8,0.583-0.883
		c0.404-0.083,0.8,0.178,0.883,0.582c6.237,30.483,33.383,52.606,64.547,52.606c30.911,0,58.012-21.909,64.439-52.096
		c0.086-0.404,0.482-0.659,0.888-0.576c0.404,0.086,0.662,0.482,0.575,0.887c-3.163,14.86-11.417,28.375-23.24,38.058
		C180.25,199.11,165.099,204.516,149.576,204.516z" id="white-curve"></path>
  </g>
  <g id="blocks">
    <g id="group1">
      <path stroke-miterlimit="10" d="M99.403,97.625c-3.514,4.462-6.337,9.246-8.488,14.226
		l8.969,3.866c1.823-4.218,4.214-8.271,7.189-12.05L99.403,97.625z" class="box1"></path>
      <path stroke-miterlimit="10" d="M208.325,162.19c-2.227,5.225-5.065,9.999-8.401,14.276
		l-7.698-6.012c2.824-3.623,5.231-7.667,7.118-12.092L208.325,162.19z" class="box1"></path>
      <path stroke-miterlimit="10" d="M208.325,112.098c-2.227-5.225-5.065-9.999-8.401-14.276
		l-7.698,6.012c2.824,3.623,5.231,7.667,7.118,12.091L208.325,112.098z" class="box1"></path>
      <path stroke-miterlimit="10" d="M99.403,176.664c-3.514-4.463-6.337-9.246-8.488-14.227
		l8.969-3.865c1.823,4.218,4.214,8.271,7.189,12.05L99.403,176.664z" class="box1"></path>
    </g>
    <g id="group2">
      <path stroke-miterlimit="10" d="M113.137,84.688c-4.665,3.241-8.763,6.991-12.274,11.124l7.449,6.32
		c2.975-3.502,6.445-6.681,10.396-9.426L113.137,84.688z" class="box2"></path>
      <path stroke-miterlimit="10" d="M198.447,178.264c-3.655,4.346-7.769,8.082-12.207,11.198
		l-5.606-7.999c3.761-2.639,7.244-5.803,10.341-9.484L198.447,178.264z" class="box2"></path>
      <path stroke-miterlimit="10" d="M198.447,96.024c-3.655-4.346-7.769-8.082-12.207-11.198
		l-5.606,7.999c3.761,2.639,7.244,5.803,10.341,9.484L198.447,96.024z" class="box2"></path>
      <path stroke-miterlimit="10" d="M113.137,189.6c-4.665-3.24-8.763-6.991-12.274-11.124l7.449-6.32
		c2.975,3.502,6.445,6.681,10.396,9.426L113.137,189.6z" class="box2"></path>
    </g>
    <g id="group3">
      <path stroke-miterlimit="10" d="M130.113,76.311c-5.409,1.731-10.428,4.115-14.997,7.038
		l5.269,8.224c3.872-2.475,8.121-4.496,12.703-5.962L130.113,76.311z" class="box3"></path>
      <path stroke-miterlimit="10" d="M184.488,190.629c-4.756,3.105-9.771,5.493-14.922,7.194
		l-3.056-9.276c4.361-1.441,8.611-3.464,12.64-6.094L184.488,190.629z" class="box3"></path>
      <path stroke-miterlimit="10" d="M184.488,83.659c-4.756-3.104-9.771-5.493-14.922-7.194
		l-3.056,9.277c4.361,1.441,8.611,3.463,12.64,6.093L184.488,83.659z" class="box3"></path>
      <path stroke-miterlimit="10" d="M130.113,197.978c-5.409-1.731-10.428-4.115-14.997-7.038
		l5.269-8.224c3.872,2.475,8.121,4.496,12.703,5.962L130.113,197.978z" class="box3"></path>
    </g>
    <g id="group4">
      <path stroke-miterlimit="10" d="M148.733,73.277c-5.678,0.075-11.173,0.89-16.397,2.349
		l2.636,9.407c4.425-1.237,9.08-1.928,13.891-1.992L148.733,73.277z" class="box1"></path>
      <path stroke-miterlimit="10" d="M167.34,198.496c-5.454,1.579-10.949,2.398-16.372,2.521
		l-0.213-9.765c4.594-0.104,9.248-0.797,13.869-2.134L167.34,198.496z" class="box1"></path>
      <path stroke-miterlimit="10" d="M167.34,75.792c-5.454-1.58-10.949-2.398-16.372-2.521
		l-0.213,9.766c4.594,0.104,9.248,0.796,13.869,2.133L167.34,75.792z" class="box1"></path>
      <path stroke-miterlimit="10" d="M148.733,201.011c-5.678-0.075-11.173-0.891-16.397-2.349
		l2.636-9.406c4.425,1.236,9.08,1.928,13.891,1.992L148.733,201.011z" class="box1"></path>
    </g>
  </g>

  <g id="el_red-hex_an_rotation" data-animator-group="true" data-animator-type="1">
    <g id="el_red-hex_an_scale" data-animator-group="true" data-animator-type="2">
      <g id="el_red-hex">
        <path d="M171.45,175.021h-43.748l-21.874-37.886l21.874-37.887h43.748l21.873,37.887L171.45,175.021z
		 M128.566,173.524h42.02l21.011-36.39l-21.011-36.391h-42.02l-21.01,36.391L128.566,173.524z" id="red-hex"></path>
      </g>
    </g>
  </g>
  <g id="el_gold-hex_an_gold-rotation" data-animator-group="true" data-animator-type="1">
    <g id="el_gold-hex_an_scale" data-animator-group="true" data-animator-type="2">
      <g id="el_gold-hex">
        <path d="M149.578,174.933l-32.735-18.896l-0.002-37.799l32.733-18.901l32.735,18.897l0.003,37.799L149.578,174.933z
		 M118.339,155.172l31.239,18.034l31.238-18.038l-0.002-36.071l-31.24-18.033l-31.237,18.038L118.339,155.172z" id="el_gold-hex-path"></path>
      </g>
    </g>
  </g>
  <g id="el_dotted-hex-group">
    <path d="M126.222,178.335c-0.259,0-0.51-0.134-0.649-0.374l-1.496-2.592c-0.206-0.357-0.084-0.814,0.274-1.021
		c0.358-0.205,0.815-0.083,1.022,0.273l1.496,2.593c0.207,0.357,0.084,0.814-0.274,1.021
		C126.477,178.303,126.349,178.335,126.222,178.335z M165.611,178.334h-2.99c-0.414,0-0.749-0.334-0.749-0.747
		s0.335-0.747,0.749-0.747h2.99c0.414,0,0.749,0.334,0.749,0.747S166.025,178.334,165.611,178.334z M155.14,178.334h-2.993
		c-0.413,0-0.746-0.334-0.746-0.747s0.333-0.747,0.746-0.747h2.993c0.414,0,0.748,0.334,0.748,0.747S155.554,178.334,155.14,178.334
		z M144.667,178.334h-2.992c-0.413,0-0.748-0.334-0.748-0.747s0.335-0.747,0.748-0.747h2.992c0.414,0,0.749,0.334,0.749,0.747
		S145.081,178.334,144.667,178.334z M134.194,178.334h-2.992c-0.413,0-0.749-0.334-0.749-0.747s0.335-0.747,0.749-0.747h2.992
		c0.414,0,0.748,0.334,0.748,0.747S134.608,178.334,134.194,178.334z M173.012,178.195c-0.128,0-0.256-0.032-0.374-0.101
		c-0.358-0.206-0.48-0.664-0.273-1.021l1.495-2.592c0.208-0.357,0.666-0.479,1.023-0.272c0.357,0.205,0.479,0.663,0.272,1.021
		l-1.496,2.591C173.522,178.061,173.27,178.195,173.012,178.195z M120.985,169.267c-0.258,0-0.51-0.135-0.648-0.374l-1.496-2.593
		c-0.207-0.358-0.084-0.814,0.274-1.021s0.815-0.083,1.021,0.273l1.496,2.593c0.207,0.358,0.084,0.814-0.274,1.021
		C121.241,169.234,121.112,169.267,120.985,169.267z M178.248,169.127c-0.128,0-0.256-0.033-0.374-0.102
		c-0.358-0.206-0.48-0.664-0.273-1.021l1.496-2.593c0.207-0.357,0.665-0.479,1.022-0.273c0.357,0.207,0.479,0.665,0.272,1.023
		l-1.495,2.591C178.757,168.992,178.506,169.127,178.248,169.127z M115.749,160.196c-0.259,0-0.51-0.135-0.648-0.374l-1.496-2.591
		c-0.207-0.359-0.084-0.815,0.274-1.022c0.359-0.207,0.815-0.083,1.022,0.273l1.495,2.591c0.207,0.358,0.084,0.816-0.273,1.022
		C116.004,160.164,115.875,160.196,115.749,160.196z M183.484,160.056c-0.128,0-0.257-0.031-0.374-0.1
		c-0.357-0.207-0.48-0.665-0.273-1.022l1.496-2.591c0.206-0.357,0.665-0.479,1.022-0.273c0.357,0.207,0.479,0.664,0.273,1.021
		l-1.497,2.591C183.993,159.921,183.741,160.056,183.484,160.056z M110.513,151.127c-0.259,0-0.51-0.134-0.649-0.373l-1.495-2.593
		c-0.207-0.358-0.084-0.815,0.273-1.021c0.358-0.207,0.815-0.083,1.021,0.273l1.497,2.592c0.207,0.358,0.084,0.815-0.274,1.021
		C110.768,151.094,110.639,151.127,110.513,151.127z M188.721,150.986c-0.127,0-0.256-0.032-0.374-0.1
		c-0.357-0.207-0.48-0.664-0.273-1.021l1.496-2.592c0.206-0.359,0.666-0.48,1.021-0.274c0.358,0.207,0.48,0.664,0.274,1.021
		l-1.496,2.592C189.23,150.853,188.979,150.986,188.721,150.986z M105.276,142.058c-0.259,0-0.51-0.135-0.648-0.374l-1.496-2.592
		c-0.207-0.357-0.084-0.814,0.274-1.021c0.359-0.208,0.816-0.085,1.022,0.272l1.496,2.591c0.207,0.357,0.084,0.816-0.273,1.021
		C105.532,142.024,105.403,142.058,105.276,142.058z M193.957,141.917c-0.128,0-0.256-0.031-0.374-0.1
		c-0.357-0.207-0.48-0.665-0.273-1.023l1.496-2.59c0.208-0.358,0.665-0.481,1.021-0.274c0.357,0.207,0.48,0.663,0.274,1.021
		l-1.496,2.592C194.467,141.782,194.215,141.917,193.957,141.917z M105.69,132.988c-0.126,0-0.255-0.033-0.373-0.101
		c-0.358-0.207-0.48-0.664-0.274-1.021l1.496-2.593c0.207-0.357,0.664-0.479,1.022-0.272c0.358,0.206,0.48,0.664,0.273,1.022
		l-1.496,2.59C106.201,132.854,105.95,132.988,105.69,132.988z M193.38,132.848c-0.258,0-0.51-0.135-0.648-0.374l-1.496-2.592
		c-0.207-0.357-0.084-0.814,0.273-1.021c0.357-0.206,0.814-0.084,1.022,0.273l1.496,2.591c0.207,0.357,0.084,0.815-0.274,1.021
		C193.636,132.815,193.507,132.848,193.38,132.848z M110.927,123.918c-0.127,0-0.256-0.032-0.373-0.1
		c-0.358-0.207-0.48-0.664-0.274-1.022l1.496-2.592c0.206-0.357,0.663-0.48,1.021-0.274c0.358,0.208,0.48,0.665,0.274,1.023
		l-1.496,2.591C111.437,123.785,111.186,123.918,110.927,123.918z M188.144,123.778c-0.259,0-0.51-0.135-0.648-0.374l-1.497-2.592
		c-0.207-0.357-0.083-0.815,0.274-1.021c0.357-0.207,0.814-0.086,1.021,0.273l1.497,2.591c0.206,0.358,0.084,0.816-0.273,1.022
		C188.398,123.745,188.271,123.778,188.144,123.778z M116.163,114.849c-0.126,0-0.255-0.032-0.373-0.101
		c-0.358-0.207-0.48-0.664-0.274-1.022l1.496-2.591c0.207-0.358,0.664-0.481,1.022-0.274c0.358,0.207,0.48,0.664,0.274,1.021
		l-1.496,2.591C116.674,114.714,116.422,114.849,116.163,114.849z M182.907,114.708c-0.259,0-0.51-0.134-0.648-0.374l-1.496-2.591
		c-0.207-0.358-0.084-0.815,0.274-1.022c0.357-0.206,0.813-0.083,1.021,0.273l1.497,2.592c0.206,0.358,0.084,0.815-0.273,1.022
		C183.162,114.676,183.035,114.708,182.907,114.708z M121.4,105.779c-0.127,0-0.256-0.032-0.374-0.1
		c-0.357-0.207-0.48-0.664-0.273-1.021l1.496-2.591c0.207-0.358,0.664-0.481,1.022-0.274c0.358,0.208,0.48,0.665,0.273,1.022
		l-1.496,2.591C121.91,105.645,121.658,105.779,121.4,105.779z M177.671,105.639c-0.259,0-0.511-0.134-0.648-0.374l-1.496-2.591
		c-0.207-0.358-0.085-0.816,0.273-1.022c0.358-0.207,0.816-0.084,1.022,0.274l1.495,2.591c0.206,0.358,0.085,0.815-0.273,1.022
		C177.927,105.607,177.798,105.639,177.671,105.639z M171.937,97.43h-2.993c-0.413,0-0.746-0.334-0.746-0.748
		s0.333-0.748,0.746-0.748h2.993c0.413,0,0.748,0.335,0.748,0.748S172.35,97.43,171.937,97.43z M161.464,97.43h-2.992
		c-0.414,0-0.748-0.334-0.748-0.748s0.334-0.748,0.748-0.748h2.992c0.413,0,0.747,0.335,0.747,0.748S161.877,97.43,161.464,97.43z
		 M150.991,97.43h-2.992c-0.413,0-0.748-0.334-0.748-0.748s0.335-0.748,0.748-0.748h2.992c0.414,0,0.749,0.335,0.749,0.748
		S151.404,97.43,150.991,97.43z M140.518,97.43h-2.992c-0.413,0-0.748-0.334-0.748-0.748s0.335-0.748,0.748-0.748h2.992
		c0.413,0,0.748,0.335,0.748,0.748S140.931,97.43,140.518,97.43z M130.046,97.43h-2.993c-0.413,0-0.748-0.334-0.748-0.748
		s0.335-0.748,0.748-0.748h2.993c0.413,0,0.748,0.335,0.748,0.748S130.459,97.43,130.046,97.43z" id="el_dotted-hex"></path>
  </g>
  <g id="logo">
    <path stroke-miterlimit="10" d="M295.668,106.873h-55.886l-5.198,9h-14.791
	c-8.058-27.411-32.09-47.972-61.332-50.94l16.618-13.261L149.616,4.25l-25.463,47.421l16.618,13.261
	c-29.242,2.969-53.274,23.53-61.332,50.94H64.648l-5.198-9H3.564" id="el_top-outline"></path>
    <path d="M149.999,147.599c0,0-1.5-0.69-3.139-1.783s-2.193-3.74-2.193-3.74c-1.215,1.25-3.334,1.5-3.334,1.5
			c-0.584-0.917,0.25-3.5,0.25-3.5c-1.334,1-3.334,1.667-3.334,1.667l-0.166-2.276l1-1.391c0,0-2.416,0.167-3.25,0
			s0.166-4.917,0.166-4.917c-5.166,1.333-15.75-4.833-17.25-5.833s-1-2.667-1-2.667s-7.082-4.833-7.416-5.631
			s0.166-1.785,0.166-1.785s-10.08-5.809-9.166-7.167c5.416-0.75,36.084,8.917,38,10.083c1.916,1.168,7.666,8.403,7.666,8.403
			l3-0.611l3,0.611c0,0,5.752-7.235,7.668-8.403c1.916-1.166,32.584-10.833,38-10.083c0.912,1.358-9.168,7.167-9.168,7.167
			s0.502,0.987,0.168,1.785s-7.418,5.631-7.418,5.631s0.5,1.667-1,2.667s-12.082,7.166-17.25,5.833c0,0,1.002,4.75,0.168,4.917
			s-3.25,0-3.25,0l1,1.391l-0.168,2.276c0,0-1.998-0.667-3.332-1.667c0,0,0.834,2.583,0.25,3.5c0,0-2.121-0.25-3.334-1.5
			c0,0-0.557,2.647-2.195,3.74S149.999,147.599,149.999,147.599z" id="el_wings"></path>
    <ellipse cx="150" cy="122.075" rx="3" ry="3.75" id="el_head"></ellipse>
    <path d="M150,126.45c2.278,0,4.583,0.913,4.583,2.708c0,3.875-2.583,5.375-2.583,6.75s1.375,1.25,1.375,5.042
			c0,1.572-1.677,19.577-2.32,23.979c-0.091,0.623-1.055,0.816-1.055,0.816s-0.964-0.193-1.055-0.816
			c-0.644-4.402-2.32-22.407-2.32-23.979c0-3.792,1.375-3.667,1.375-5.042s-2.583-2.875-2.583-6.75
			C145.417,127.363,147.722,126.45,150,126.45z" id="el_body"></path>
  </g>
</svg>

app/views/layouts/_navigation.html.erb
<% if origin != 'admin' %>
  <% subjects ||= [] %>
  <% evenSubjects, oddSubjects = subjects.partition.with_index { |_,i| i.even? } %>
  <div id="even"; >
    <%= render partial: 'layouts/navigation_subject', locals: {subjects: evenSubjects} %>
  </div>
  <div id="odd">
    <%= render partial: 'layouts/navigation_subject', locals: {subjects: oddSubjects} %>
  </div>
<% else %>
  <div id="even">
    <div class="navigation subject">
      <div class="subject name">
        <b>Manage</b>
      </div>
      <div class="pages">
        <ul>
          <li><%= link_to_unless_current('Admins', admin_users_path, {remote: true}) %></li>
          <li><%= link_to_unless_current('Content', subjects_path, {remote: true}) %></li>
        </ul>
      </div>
    </div>
  </div>
  <div id="odd" >
    <div class="navigation subject">
      <div class="subject name">
        <b>Actions</b>
      </div>
      <div class="pages">
        <ul>
          <% if session[:user_id] %>
            <li><%= link_to_unless_current('Logout', access_logout_path) %></li>
          <% else %>
            <li><%= link_to_unless_current('Login', access_login_path) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation_subject.html.erb
<% subjects.each do |s| %>
  <div class="navigation subject">
    <div class="subject name">
      <b><%= s.name %></b>
    </div>
    <div class="pages">
      <ul>
        <% s.pages.visible.sorted.each do |p| %>
          <li>
            <%=
              link_to_unless_current(
                  p.name.downcase,
                  public_show_path(p.permalink), {remote: true, onclick: "toggle('expanded')"}
              )
            %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prophets CMS &spades; <%= @page_title || 'Admin Area' %></title>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag('//cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.css', media: 'all') %>
    <%= stylesheet_link_tag('admin', media: 'all') %>
    <%= favicon_link_tag('') %>
  </head>

  <body class="expanded">
    <div id="header">
      <%= render partial: 'layouts/headers', locals: {origin: 'admin'} %>
      <div id="introduction">
        <h1 id="name">Prophets CMS</h1>
      </div>
    </div>

    <div id="main">
      <div id="content">
        <% if flash[:notice].present? %>
          <div class="notice">
            <%= flash[:notice] %>
          </div>
        <% elsif flash[:error].present? %>
          <div class="error">
            <%= flash[:error] %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>

    <%= render partial: 'layouts/footer' %>
  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prophets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header">
      <h1>Prophets</h1>
    </div>
    <div id="main">

      <div id="content">
        <%= yield %>
      </div>live

    </div>

    <div id="footer">
      <p id="copyright">&copy;prophets.nl</p>
    </div>

  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prophets &spades; <%= "#{@page_title}" if @page_title %></title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag('//cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.css', media: 'all') %>
  <%= stylesheet_link_tag('application', media: 'all') %>
  <%= favicon_link_tag('') %>
</head>

<body class=<%= controller_name == 'public' && action_name == 'index' ? '' : 'expanded'%>>
  <div id="void"></div>
  <div id="header">
    <%= render partial: 'layouts/headers', locals: {origin: 'public'} %>
    <div id="introduction">
      <h1 id="name">Danny Oosthoek</h1>
      <h2 id="job-title">Ruby on Rails Developer</h2>
    </div>
  </div>
  <div id="void2"></div>

  <div id="main">
    <div id="content">
      <%= yield %>
    </div>
  </div>

  <%= render partial: 'layouts/footer' %>

</body>

</html>